In [7]:
# pi3 install jupyter
# pip3 install numpy 
# pip3 install pandas
# 启动 jupyter 
# 在工作目录下启动 jupyte notebook

# numpy 一个多维的数组，只是在原来的list上做了一些分装，提供了非常便利的科学运算功能
# pandas 侧重于数据处理，清洗
# pandas用户指南，https://pandas.pydata.org/docs/user_guide/index.html

# Shift + 回车  //执行
# all + 回车


import numpy as np
import pandas as pd 

print(1211212121)



1211212121


In [16]:
# a = np.array()   # 报错，选中 array() 按 shift + tab ,显示函数array参数信息，便于定位或修改。

a = np.array([1,2,3,4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
b = np.array([[[1,2],[3,4],[5,6]]])
b.ndim  # 查看数据维度

3

In [24]:
b.dtype

dtype('int32')

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [28]:
np.random.randn(6,4)

array([[ 0.17456244,  1.11781065, -1.47141636, -0.35115272],
       [ 1.14040353,  1.34425734,  1.83383668, -0.36580451],
       [-0.14024266, -1.70936399,  0.49956777,  1.25749178],
       [-1.28500841, -0.38692749,  1.8881775 ,  0.22967062],
       [ 0.05590032,  1.00824817, -0.40479993, -1.51433327],
       [ 0.13224976,  0.56683938, -0.21911269, -0.32850995]])

In [31]:
### 【amdas 简介
# - 是一个专注于数据处理的一个库
# - 可以帮助数据分析、数据挖掘、算法工程师的人员其高耸的姐姐数据预处理的问题
###

In [33]:
# pandas 的第一个数据类型Series
obj = pd.Series([1,2,3,4,5])
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [34]:
obj[0]

1

In [35]:
obj[[0,2,4]]  # 注意，这里是两个括号，因为要取出来多个位置的元素时，接收的时一个list

0    1
2    3
4    5
dtype: int64

In [39]:
obj2 = pd.Series({"姓名":"张三","年龄":"12"})
obj2

姓名    张三
年龄    12
dtype: object

In [40]:
obj2["姓名"]

'张三'

In [43]:
obj2[["姓名","年龄"]]

姓名    张三
年龄    12
dtype: object

In [45]:
obj3 = pd.Series(["夏雨荷","山东",19],index=["姓名","地址","年龄"])
obj3

姓名    夏雨荷
地址     山东
年龄     19
dtype: object

In [56]:
# pandas结合这Numpy来进行数学运算
number1 = pd.Series([4,8,16,32])
np.log2(number1)  # 对数运算
a = np.log2(number1)  # 对数运算
type(a)

pandas.core.series.Series

In [55]:
# dataFrame
df1 = pd.DataFrame([["张无忌",24,"男"],["谢逊",54,"男"],["周芷若",16,"女"]])
df1

0   1  2
0  张无忌  24  男
1   谢逊  54  男
2  周芷若  16  女

In [58]:
# 使用字典进行构造
data = {
    "人物":["张三丰","张无忌","张翠山"],
    "风景":["武当山","桃花岛","冰火岛"]
}
df2 = pd.DataFrame(data)
df2

人物   风景
0  张三丰  武当山
1  张无忌  桃花岛
2  张翠山  冰火岛

In [59]:
df2["人物"]

0    张三丰
1    张无忌
2    张翠山
Name: 人物, dtype: object

In [60]:
df2["人物"][1]

'张无忌'

In [61]:
np_data = [["张无忌",24,"男"],["谢逊",54,"男"],["周芷若",16,"女"]]
df3 = pd.DataFrame(np_data)
df3

0   1  2
0  张无忌  24  男
1   谢逊  54  男
2  周芷若  16  女

In [63]:
# 读取csv文件
pd.read_csv("data.csv")

a   b   c   d   e   f
0   1   2   3   4   5   6
1  10  11  12  13  14  15

In [67]:
# 将第一行标题作为数据
pd.read_csv("data.csv", header=None)

0   1   2   3   4   5
0   a   b   c   d   e   f
1   1   2   3   4   5   6
2  10  11  12  13  14  15

In [77]:
# 指定c这列作为索引
pd.read_csv("data.csv",index_col='c')


a   b   d   e   f
c                     
3    1   2   4   5   6
12  10  11  13  14  15

In [78]:
a = pd.read_csv("data.csv",index_col='c')
type(a)

pandas.core.frame.DataFrame

In [79]:
pd.read_csv("data.csv", header=None)[0][0]


'a'

In [85]:
# 行列数
csv = pd.read_csv("data.csv")
csv.shape

(2, 6)

In [86]:
# 每一列的数据类型
csv.dtypes 

a    int64
b    int64
c    int64
d    int64
e    int64
f    int64
dtype: object

In [87]:
# 显示b列的数据及类型
csv.b

0     2
1    11
Name: b, dtype: int64

In [89]:
# 数据统计性描述
csv.describe()

a          b          c          d          e          f
count   2.000000   2.000000   2.000000   2.000000   2.000000   2.000000
mean    5.500000   6.500000   7.500000   8.500000   9.500000  10.500000
std     6.363961   6.363961   6.363961   6.363961   6.363961   6.363961
min     1.000000   2.000000   3.000000   4.000000   5.000000   6.000000
25%     3.250000   4.250000   5.250000   6.250000   7.250000   8.250000
50%     5.500000   6.500000   7.500000   8.500000   9.500000  10.500000
75%     7.750000   8.750000   9.750000  10.750000  11.750000  12.750000
max    10.000000  11.000000  12.000000  13.000000  14.000000  15.000000

In [91]:
dates = pd.date_range("20201127",periods=6)
dates

DatetimeIndex(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
               '2020-12-01', '2020-12-02'],
              dtype='datetime64[ns]', freq='D')

In [93]:
# 随机生成6行4列的随机数，索引号显示dates的日期，列名显示ABCD
df = pd.DataFrame(np.random.rand(6,4),index=dates,columns=list("ABCD"))
df

A         B         C         D
2020-11-27  0.279630  0.104162  0.585856  0.881266
2020-11-28  0.093147  0.314897  0.867012  0.482435
2020-11-29  0.284225  0.281333  0.112428  0.226839
2020-11-30  0.342760  0.211604  0.429439  0.514805
2020-12-01  0.307594  0.923725  0.177073  0.357767
2020-12-02  0.112103  0.526397  0.369634  0.004998

In [94]:
# 转置，行列切换（与93对比一下）
df.T

2020-11-27  2020-11-28  2020-11-29  2020-11-30  2020-12-01  2020-12-02
A    0.279630    0.093147    0.284225    0.342760    0.307594    0.112103
B    0.104162    0.314897    0.281333    0.211604    0.923725    0.526397
C    0.585856    0.867012    0.112428    0.429439    0.177073    0.369634
D    0.881266    0.482435    0.226839    0.514805    0.357767    0.004998

In [95]:
# 显示区间里的记录
df["2020-11-27":"2020-11-29"]

A         B         C         D
2020-11-27  0.279630  0.104162  0.585856  0.881266
2020-11-28  0.093147  0.314897  0.867012  0.482435
2020-11-29  0.284225  0.281333  0.112428  0.226839

In [96]:
# 对列进行筛选
df.loc["2020-11-27":"2020-11-29",["A","B"]]

A         B
2020-11-27  0.279630  0.104162
2020-11-28  0.093147  0.314897
2020-11-29  0.284225  0.281333

In [97]:
# at对行列值的选择
df.at[dates[0],"A"]

0.2796300210858449

In [100]:
df.at[dates[1],"B"]

0.3148965678468616

In [101]:
# 显示头部N条记录
df.head(2)

A         B         C         D
2020-11-27  0.279630  0.104162  0.585856  0.881266
2020-11-28  0.093147  0.314897  0.867012  0.482435

In [102]:
# 显示尾部N条记录
df.tail(3)

A         B         C         D
2020-11-30  0.342760  0.211604  0.429439  0.514805
2020-12-01  0.307594  0.923725  0.177073  0.357767
2020-12-02  0.112103  0.526397  0.369634  0.004998

In [104]:
# pandas 重新索引
obj = pd.Series([4.5,9.4,-2.3],index=["a","b","c"])
obj

a    4.5
b    9.4
c   -2.3
dtype: float64

In [107]:
# NaN表示空，表示某个索引不存在，缺省值NaN
obj_1 = obj.reindex(["a","b","c","d","e"])
obj_1

a    4.5
b    9.4
c   -2.3
d    NaN
e    NaN
dtype: float64

In [108]:
# 对缺省值设置默认值，如0
obj_1 = obj.reindex(["a","b","c","d","e"], fill_value=0)
obj_1

a    4.5
b    9.4
c   -2.3
d    0.0
e    0.0
dtype: float64

In [139]:
# 旅游网站数据清洗实战
df = pd.read_csv("icd.csv",index_col=0)   # 去掉索引
df.head()

attachCode                     name  level
mainCode                                             
A00.000            NaN   霍乱，由于O1群霍乱弧菌，霍乱生物型所�?5   NaN
A00.100            NaN  霍乱，由于O1群霍乱弧菌，埃尔托生物型所�?5   NaN
A00.900            NaN                       霍乱     5
A01.000            NaN                       伤寒     5
A01.001+        K77.0*                  伤寒性肝�?5   NaN

In [123]:
df.shape

(23088, 6)

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23088 entries, A00.000 to I15.9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   attachCode  3116 non-null   object
 1   name        23088 non-null  object
 2   level       10699 non-null  object
dtypes: object(3)
memory usage: 721.5+ KB


In [136]:
df.describe()

attachCode   name  level
count        3116  23088  10699
unique       2622  22725     34
top        G99.2*  恶性淋巴瘤      5
freq           18     13  10628

In [140]:
# 把所有的列列出来
# 注意部分列名前后有多余的空格
df.columns

Index([' attachCode ', ' name ', 'level'], dtype='object')

In [141]:
df.columns.values

array([' attachCode ', ' name ', 'level'], dtype=object)

In [142]:
col = df.columns.values
col[0].strip()

'attachCode'

In [143]:
# 批量清除列名前后空格
df.columns = [x.strip() for x in col]
df.columns.values

array(['attachCode', 'name', 'level'], dtype=object)