In [1]:
import numpy as np

In [7]:
n = np.array([[5, 10, 15],
              [20, 125, 30],
              [35, 40, 45]])

In [8]:
n.min()

5

In [9]:
n.max()

125

In [72]:
# 某一行中最大值组成数组
n.max(axis=0)

array([ 35, 125,  45])

In [12]:
# 某一列中最大值组成数组
n.max(1)

array([ 15, 125,  45])

In [14]:
n.mean().round(2)

36.11

In [22]:
# 列求和组成数组  
n.sum(axis=0)

array([ 60, 175,  90])

In [17]:
# 行求和组成数组
n.sum(1)

array([ 30, 175, 120])

In [18]:
n.sum()

325

In [19]:
# 列求平均值组成数组
n.mean(0)

array([20.        , 58.33333333, 30.        ])

In [20]:
# 行求平均值组成数组
n.mean(1)

array([10.        , 58.33333333, 40.        ])

In [31]:
n1 = np.arange(5)

In [32]:
n1

array([0, 1, 2, 3, 4])

In [33]:
# np. exp(x)   e的x幂次方
np.exp(n1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [34]:
# 开根号
np.sqrt(n1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [38]:
# np.floor() 向下取整
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

In [39]:
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [74]:
# 排序
a = np.array([[4, 3, 5], [1, 6, 1]])
a

array([[4, 3, 5],
       [1, 6, 1]])

In [75]:
# 行排序
np.sort(a)  # 等同于 np.sort(a,1)   或 np.sort(a,axis=1)

array([[3, 4, 5],
       [1, 1, 6]])

In [76]:
# 列排序
np.sort(a)

array([[3, 4, 5],
       [1, 1, 6]])

In [63]:
# np.argsort() 返回元素位置的排序索引
x = np.array([44, 23, 10, 24])
arg = np.argsort(x)
arg

array([2, 1, 3, 0], dtype=int64)

In [64]:
x[arg]

array([10, 23, 24, 44])

In [65]:
np.argsort(arg)  # 对 array([2, 1, 3, 0], dtype=int64) 进行再索引排序

array([3, 1, 0, 2], dtype=int64)

In [66]:
# 返回数组[44, 23, 10, 24]中最大值的索引号
arg[-1]

0

In [68]:
# 返回数组中最小值的索引号
arg[0]

2

In [79]:
# 返回数组中最大元素的索引
a = np.array([44, 23, 3310, 124])
a.argmax()

2

In [80]:
a.argmin()

1

In [85]:
n1 = np.array([[11, 1],
               [0, 5]])
n2 = np.array([[2, 0],
               [3, 4]])

In [86]:
n1

array([[11,  1],
       [ 0,  5]])

In [87]:
n2

array([[2, 0],
       [3, 4]])

In [88]:
# [11*2,1*0],[0*3,5*4]
n1*n2

array([[22,  0],
       [ 0, 20]])

In [89]:
np.multiply(n1,n2)

array([[22,  0],
       [ 0, 20]])

In [90]:
np.multiply(2, 3)

6

In [91]:
np.multiply(n1, 3)

array([[33,  3],
       [ 0, 15]])

In [92]:
A = np.array( [[1,2],
               [3,4]] )
B = np.array( [[5,6],
               [7,8]] )

In [93]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [95]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [141]:
a= np.ones((3,7))

In [142]:
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [143]:
b= np.ones((7,3))*4

In [144]:
b

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [145]:
a.dot(b)

array([[28., 28., 28.],
       [28., 28., 28.],
       [28., 28., 28.]])

In [122]:
A=[1,2,3,4,5]
B=[5,4,3,2,1]

In [124]:
np.dot(A,B)

35

In [125]:
A=np.array([1,2,3,4]).reshape(4,1)
B=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)

In [129]:
A

array([[1],
       [2],
       [3],
       [4]])

In [130]:
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
# 报错了，A·B中, 因为A的x方向为1个元素，而B的y方向为2个元素。无法进行点积运算。
np.dot(A,B)

ValueError: shapes (4,1) and (2,4) not aligned: 1 (dim 1) != 2 (dim 0)

In [132]:
# B·A中，B的x方向有4个元素，A的y方向有四个元素。
# 最终的结果，C在y方向上跟随B，有两个元素；在x方向上跟随A，有一个元素。C：(2,1)。
np.dot(B,A)

array([[30],
       [70]])

In [146]:
A1=np.array([1,2]).reshape(2,1)
W=np.array([1,2,3,4,5,6]).reshape(3,2)
print('A2=W·A1:\n',np.dot(W,A1))

A2=W·A1:
 [[ 5]
 [11]
 [17]]


In [147]:
A1


array([[1],
       [2]])

In [148]:
W

array([[1, 2],
       [3, 4],
       [5, 6]])

In [153]:
np.matmul(W,A1)

array([[ 5],
       [11],
       [17]])

In [154]:
n1 = np.array([[10, 11],
               [12, 13]])
n2 = np.array([[40, 51],
               [62, 73]])

In [156]:
# 横拼接
np.hstack((n1,n2))

array([[10, 11, 40, 51],
       [12, 13, 62, 73]])

In [157]:
# 竖拼接
np.vstack((n1,n2))

array([[10, 11],
       [12, 13],
       [40, 51],
       [62, 73]])

In [159]:
n3 = np.floor(10 * np.random.random((2, 12)))
n3

array([[7., 8., 5., 6., 0., 4., 0., 8., 7., 7., 9., 9.],
       [3., 8., 1., 9., 1., 1., 5., 1., 8., 6., 9., 5.]])

In [160]:
np.hsplit(n3,3)

[array([[7., 8., 5., 6.],
        [3., 8., 1., 9.]]),
 array([[0., 4., 0., 8.],
        [1., 1., 5., 1.]]),
 array([[7., 7., 9., 9.],
        [8., 6., 9., 5.]])]

In [161]:
np.hsplit(n3,(3,5))

[array([[7., 8., 5.],
        [3., 8., 1.]]),
 array([[6., 0.],
        [9., 1.]]),
 array([[4., 0., 8., 7., 7., 9., 9.],
        [1., 5., 1., 8., 6., 9., 5.]])]

In [162]:
n3.T

array([[7., 3.],
       [8., 8.],
       [5., 1.],
       [6., 9.],
       [0., 1.],
       [4., 1.],
       [0., 5.],
       [8., 1.],
       [7., 8.],
       [7., 6.],
       [9., 9.],
       [9., 5.]])

In [163]:
np.vsplit(n3.T,3)

[array([[7., 3.],
        [8., 8.],
        [5., 1.],
        [6., 9.]]),
 array([[0., 1.],
        [4., 1.],
        [0., 5.],
        [8., 1.]]),
 array([[7., 8.],
        [7., 6.],
        [9., 9.],
        [9., 5.]])]

In [168]:
harr = np.floor(10 * np.random.random((2, 6)))
harr


array([[9., 2., 1., 9., 8., 0.],
       [7., 4., 0., 1., 0., 4.]])

In [169]:
np.hsplit(harr, 3)

[array([[9., 2.],
        [7., 4.]]),
 array([[1., 9.],
        [0., 1.]]),
 array([[8., 0.],
        [0., 4.]])]

In [171]:
np.hsplit(harr, (2, 4, 5))

[array([[9., 2.],
        [7., 4.]]),
 array([[1., 9.],
        [0., 1.]]),
 array([[8.],
        [0.]]),
 array([[0.],
        [4.]])]

In [172]:
x = np.arange(16.0).reshape(2, 8)

In [173]:
x

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [184]:
np.hsplit(x, [1,2,6])

[array([[0.],
        [8.]]),
 array([[1.],
        [9.]]),
 array([[ 2.,  3.,  4.,  5.],
        [10., 11., 12., 13.]]),
 array([[ 6.,  7.],
        [14., 15.]])]

In [190]:
n = np.array([-0.746, 4.6, 9.4, 7.447, 10.455, 121.555])


In [191]:
np.around(n, decimals=-1)


array([ -0.,   0.,  10.,  10.,  10., 120.])

In [192]:
n = np.array([-1.7, -2.5, -0.2, 0.6, 1.2, 2.7, 11])


In [193]:
np.ceil(n)

array([-1., -2., -0.,  1.,  2.,  3., 11.])

In [194]:
data = np.random.random([2, 3])
data

array([[0.12858328, 0.80317375, 0.67889686],
       [0.31372941, 0.08821488, 0.25861198]])

In [197]:
np.where(data>0.5,data,0)

array([[0.        , 0.80317375, 0.67889686],
       [0.        , 0.        , 0.        ]])

In [199]:
np.array([[i, i * i] for i in [5, 6, 7]])


array([[ 5, 25],
       [ 6, 36],
       [ 7, 49]])

In [200]:
np.arange(9.).reshape(3, 3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [201]:
np.arange(2, 10, 2)


array([2, 4, 6, 8])

In [202]:
np.arange(start=2, stop=10, step=2)


array([2, 4, 6, 8])

In [203]:
np.empty(shape=3)

array([8.56335344e-312, 0.00000000e+000, 2.52616730e-296])

In [204]:
np.empty(shape=(2,3))

array([[0.        , 0.80317375, 0.67889686],
       [0.        , 0.        , 0.        ]])

In [205]:
np.empty(shape=(2,3),dtype=int)

array([[-1924755376,         403,           0],
       [          0,           1,    43025764]])

In [206]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [209]:
np.ones(5).dtype

dtype('float64')

In [211]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [213]:
n1=np.arange(0,40,10)

In [214]:
np.tile(n1,(3,5))

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,
         0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,
         0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30,
         0, 10, 20, 30]])

In [215]:
np.r_[[1,2,3],[4,5,6],[7,8,9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
a = np.array([[1, 2, 3],[7,8,9]])
b=np.array([[4,5,6],[1,2,3]])

In [222]:
np.r_[a,b]


array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [223]:
 np.linspace(-5, 5, 5)

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [224]:
 np.linspace(-5, 5, 5, False)

array([-5., -3., -1.,  1.,  3.])

In [225]:
 np.linspace(-5, 5, 5, False,True)

(array([-5., -3., -1.,  1.,  3.]), 2.0)

In [226]:
 np.linspace(-5, 5, 5, False,True,int)

(array([-5, -3, -1,  1,  3]), 2.0)