In [2]:
# pi3 install jupyter
# pip3 install numpy 
# pip3 install pandas
# 启动 jupyter 
# 在工作目录下启动 jupyte notebook

# numpy 数学库，用于数组计算（一维、二维、多维），对list进行部分封装，提供了非常便利的科学运算功能，
# 因此在数值计算，机器学习，人工智能，神经网络等领域广泛应用。
# Numpy的核心是 ndarray，array本质是数组
# 官网：https://numpy.org/doc/stable/reference/

# pandas 侧重于数据处理，清洗
# pandas用户指南，https://pandas.pydata.org/docs/user_guide/index.html
# Shift + 回车  //执行
# all + 回车

import numpy as np
import pandas as pd 

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.array([[[1,2.0],[1,2],[5,6]]])
print(b)

[[[1. 2.]
  [1. 2.]
  [5. 6.]]]


In [6]:
b.ndim  # 查看数据维度

3

In [7]:
print(b.dtype)

float64


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# linspace等差数列
np.linspace(0,4,num=11)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [10]:
np.linspace(0,2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [11]:
# 随机数
np.random.randn(6,4)

array([[-0.2402755 , -0.95064141, -0.2505037 , -0.95542135],
       [ 0.19045965, -0.10697575,  0.22862374, -1.06497159],
       [ 1.64057206,  0.67361388, -2.29723604,  0.39454837],
       [ 1.58142135, -1.03073138, -0.49559381, -0.03528533],
       [-1.0168809 , -0.7085316 , -1.48376019, -0.2895331 ],
       [-0.18679586,  0.72597505,  0.95632704, -0.10347095]])

In [12]:
np.random.randn(3,6,4)

array([[[-1.61025656, -0.84823714, -0.11514809,  1.68410714],
        [-2.11519223, -0.39996844, -0.27339122, -0.77331843],
        [-0.46354734, -0.11003234, -2.26119955,  1.01147355],
        [-0.56848746, -0.98407306,  1.1652457 , -0.62667471],
        [-0.67165516,  0.74672919,  0.59525441,  0.94924   ],
        [-1.62881228,  0.31133459,  0.19235463, -1.23748683]],

       [[-1.32137921,  1.11677091, -0.09411562,  0.11058346],
        [ 0.4233317 , -0.15729401, -0.86097549,  0.6088838 ],
        [ 0.79244715, -0.72660348,  1.23825356,  1.14331246],
        [-0.5167269 ,  1.1281623 ,  1.57980052, -0.61718656],
        [ 1.30903898,  1.62887419, -1.79687134, -0.01644897],
        [-1.06031177,  0.08876304, -0.66075185, -0.24522939]],

       [[-0.23793418, -1.32162756,  0.78296258, -0.81600265],
        [-0.01566881, -0.56465772,  0.18027626, -0.92130586],
        [-0.86042816,  0.5555822 , -0.39328961,  1.02105689],
        [ 0.46619813, -0.09184135,  0.78711267,  1.2391498 ],
    

In [13]:
# randint随机生成[0,1)之间的整数，就是0
np.random.randint(1,size=5)

array([0, 0, 0, 0, 0])

In [14]:
# randint随机生成[1,5)之间的整数
np.random.randint(1,5)

1

In [15]:
# randint随机生成[-5，5)之间的整数
np.random.randint(-5,5,size=(3,2))

array([[ 4,  0],
       [-2, -5],
       [-2,  1]])

In [16]:
### pandas 简介
# - 是一个专注于数据处理的一个库
# - 可以帮助数据分析、数据挖掘、算法工程师的人员
# Pandas模块的数据结构主要有两种：1.Series 2.DataFrame
###

In [17]:
# Series是一维数组，基于numpy的ndarray结构
# np.nan是一个float类型的数据
obj = pd.Series([1,2,3,4,5,np.nan])
obj

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64

In [18]:
obj = pd.Series([1,2,3,4,5])
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
np.sum(obj)

15

In [20]:
obj[4]

5

In [21]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [22]:
obj[[0,2,4]]

0    1
2    3
4    5
dtype: int64

In [23]:
d = {"a":10, "b":20, "c":30}
d = pd.Series(d)
d

a    10
b    20
c    30
dtype: int64

In [24]:
d.values

array([10, 20, 30], dtype=int64)

In [25]:
d["a"]

10

In [26]:
d[0]

10

In [27]:
d.index

Index(['a', 'b', 'c'], dtype='object')

In [28]:
i = ["jinhao","zhaoyun","xiaodong","yangyang","test"]
a = pd.Series([1,5,5,5,2],index = i)
a

jinhao      1
zhaoyun     5
xiaodong    5
yangyang    5
test        2
dtype: int64

In [29]:
# 查看表格列表中有多少个不同值的方法。并计算每个不同值在列表中有多少重复值。
a.value_counts()

5    3
1    1
2    1
dtype: int64

In [30]:
a.value_counts(ascending=True)

1    1
2    1
5    3
dtype: int64

In [31]:
# 函数dtype()数据类型
# NumPy 数字类型是dtype(数据类型)对象的实例，每个对象具有唯一的特征。 这些类型可以是np.bool_，np.float32等。
# 语法：numpy.dtype(object, align, copy)
# 每个内建类型都有一个唯一定义它的字符代码：
# ‘b’：布尔值
# ‘i’：符号整数
# ‘u’：无符号整数
# ‘f’：浮点
# ‘c’：复数浮点
# ‘m’：时间间隔
# ‘M’：日期时间
# ‘O’：Python 对象
# ‘S’, ‘a’：字节串
# ‘U’：Unicode
# ‘V’：原始数据(void)
np.dtype(np.int32)  #  # #int8，int16，int32，int64 可替换为等价的字符串 'i1'，'i2'，'i4'，以及其他。

dtype('int32')

In [32]:
np.dtype("i4")

dtype('int32')

In [33]:
np.dtype(np.float32)

dtype('float32')

In [34]:
np.dtype("f4")

dtype('float32')

In [35]:
# 结构化数组类型
student = np.dtype([("name","S20"),("age", np.int8),("marks","f4")])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [36]:
a = np.array([("abc",21,50),("xyz",18,75)], dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [37]:
print(a["name"])

[b'abc' b'xyz']


In [38]:
obj2 = pd.Series({"姓名":"张三","年龄":"12"})
obj2

姓名    张三
年龄    12
dtype: object

In [39]:
obj2[["姓名","年龄"]]

姓名    张三
年龄    12
dtype: object

In [40]:
obj3 = pd.Series(["张三","上海",22],index=["姓名","地区","年龄"])
obj3

姓名    张三
地区    上海
年龄    22
dtype: object

In [41]:
num = pd.Series([4,8,16,32])
a = np.log2(num)  # 对数函数log2()
a


0    2.0
1    3.0
2    4.0
3    5.0
dtype: float64

In [42]:
# DataFrame 二维数组
d1 = pd.DataFrame([["张无忌",24,"男"],["周芷若",16,"女"]])
d1

0   1  2
0  张无忌  24  男
1  周芷若  16  女

In [43]:
data = {"人物":["张无忌","周芷若"],"年龄":[24,16]}
d2 = pd.DataFrame(data)
d2

人物  年龄
0  张无忌  24
1  周芷若  16

In [44]:
data2 = [["张无忌","周芷若"],[24,16]]
df3 = pd.DataFrame(data2,index=list("ab"),columns=list("CD"))
df3

C    D
a  张无忌  周芷若
b   24   16

In [45]:
df3["D"][0]

'周芷若'

In [49]:
# 读取csv文件
import pandas as pd 
a = pd.read_csv("data.csv")
a

a   b   c   d   e   f
0   1   2   3   4   5   6
1  10  11  12  13  14  15

In [50]:
a["b"][1]

11

In [6]:
pd.read_csv("data.csv", header = None)[2][1]

'3'

In [105]:
# index_col 指定某一列作为索引号
f = pd.read_csv("data.csv")
f

a   b   c   d   e   f
0   1   2   3   4   5   6
1  10  11  12  13  14  15

In [106]:
f.index

RangeIndex(start=0, stop=2, step=1)

In [107]:
f = pd.read_csv("data.csv",index_col=0)
f

b   c   d   e   f
a                     
1    2   3   4   5   6
10  11  12  13  14  15

In [95]:
f.reset_index(drop=False)

a   b   c   d   e   f
0   1   2   3   4   5   6
1  10  11  12  13  14  15

In [108]:
f.index

Int64Index([1, 10], dtype='int64', name='a')

In [73]:
f.reset_index(drop=False)

a   b   c   d   e   f
0   1   2   3   4   5   6
1  10  11  12  13  14  15

In [74]:
f.index

Int64Index([1, 10], dtype='int64', name='a')

In [52]:
f["b"][10]

11

In [10]:
f.shape

(2, 5)

In [11]:
f = pd.read_csv("data.csv",index_col='c')
f

a   b   d   e   f
c                     
3    1   2   4   5   6
12  10  11  13  14  15

In [12]:
type(f)

pandas.core.frame.DataFrame

In [13]:
f.dtypes

a    int64
b    int64
d    int64
e    int64
f    int64
dtype: object

In [16]:
f.a

c
3      1
12    10
Name: a, dtype: int64

In [18]:
# 数据统计性描述
# std 标准差是方差的算术平方根，标准差是反应一个数据集合的离散程度
f.describe()

a          b          d          e          f
count   2.000000   2.000000   2.000000   2.000000   2.000000
mean    5.500000   6.500000   8.500000   9.500000  10.500000
std     6.363961   6.363961   6.363961   6.363961   6.363961
min     1.000000   2.000000   4.000000   5.000000   6.000000
25%     3.250000   4.250000   6.250000   7.250000   8.250000
50%     5.500000   6.500000   8.500000   9.500000  10.500000
75%     7.750000   8.750000  10.750000  11.750000  12.750000
max    10.000000  11.000000  13.000000  14.000000  15.000000

In [21]:
dates = pd.date_range("20201127", periods=6)
dates

DatetimeIndex(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
               '2020-12-01', '2020-12-02'],
              dtype='datetime64[ns]', freq='D')

In [22]:
import numpy as np
df = pd.DataFrame(np.random.rand(6,4),index=dates,columns=list("ABCD"))
df

A         B         C         D
2020-11-27  0.215688  0.266726  0.674841  0.077029
2020-11-28  0.988364  0.911026  0.725673  0.926905
2020-11-29  0.009441  0.413462  0.057774  0.893856
2020-11-30  0.198755  0.901874  0.694900  0.070286
2020-12-01  0.408078  0.570654  0.698506  0.082408
2020-12-02  0.639141  0.892273  0.022711  0.322303

In [23]:
type(df)

pandas.core.frame.DataFrame

In [24]:
# 转置行列切换
df.T

2020-11-27  2020-11-28  2020-11-29  2020-11-30  2020-12-01  2020-12-02
A    0.215688    0.988364    0.009441    0.198755    0.408078    0.639141
B    0.266726    0.911026    0.413462    0.901874    0.570654    0.892273
C    0.674841    0.725673    0.057774    0.694900    0.698506    0.022711
D    0.077029    0.926905    0.893856    0.070286    0.082408    0.322303

In [25]:
df["2020-11-27":"2020-11-29"]

A         B         C         D
2020-11-27  0.215688  0.266726  0.674841  0.077029
2020-11-28  0.988364  0.911026  0.725673  0.926905
2020-11-29  0.009441  0.413462  0.057774  0.893856

In [29]:
# loc 通过行索引找到具体的数据
df.loc["2020-11-27":"2020-11-29",["A","B"]] 

A         B
2020-11-27  0.215688  0.266726
2020-11-28  0.988364  0.911026
2020-11-29  0.009441  0.413462

In [30]:
df.loc["2020-11-27",["D"]]

D    0.077029
Name: 2020-11-27 00:00:00, dtype: float64

In [31]:
df.loc[:,["A"]]

A
2020-11-27  0.215688
2020-11-28  0.988364
2020-11-29  0.009441
2020-11-30  0.198755
2020-12-01  0.408078
2020-12-02  0.639141

In [32]:
df.loc["2020-11-27"]

A    0.215688
B    0.266726
C    0.674841
D    0.077029
Name: 2020-11-27 00:00:00, dtype: float64

In [33]:
dates

DatetimeIndex(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
               '2020-12-01', '2020-12-02'],
              dtype='datetime64[ns]', freq='D')

In [35]:
df.at[dates[0],"A"]

0.21568815750638481

In [36]:
df.at["2020-11-27","A"]

0.21568815750638481

In [37]:
df.head(2)

A         B         C         D
2020-11-27  0.215688  0.266726  0.674841  0.077029
2020-11-28  0.988364  0.911026  0.725673  0.926905

In [38]:
df.tail(3)

A         B         C         D
2020-11-30  0.198755  0.901874  0.694900  0.070286
2020-12-01  0.408078  0.570654  0.698506  0.082408
2020-12-02  0.639141  0.892273  0.022711  0.322303

In [39]:
# pandas 重新索引
obj = pd.Series([4.5,9.4,-2.3],index=["a","b","c"])
obj

a    4.5
b    9.4
c   -2.3
dtype: float64

In [40]:
# NaN空值
obj1 = obj.reindex(["a","b","c","d","e"])
obj1

a    4.5
b    9.4
c   -2.3
d    NaN
e    NaN
dtype: float64

In [42]:
obj1 = obj.reindex(["a","b","c","d","e"],fill_value=2)
obj1

a    4.5
b    9.4
c   -2.3
d    2.0
e    2.0
dtype: float64

In [59]:
# 旅游网址数据清洗实战
df = pd.read_csv("tr.csv")
df

出发地   目的地    价格       节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4   NaN   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
6    上海   纽约  47000   500.0        大连-烟台3天2晚
7    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [60]:
df.shape

(8, 5)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   出发地     7 non-null      object 
 1    目的地    7 non-null      object 
 2   价格      8 non-null      int64  
 3    节省     6 non-null      float64
 4   路线名     8 non-null      object 
dtypes: float64(1), int64(1), object(3)
memory usage: 448.0+ bytes


In [62]:
df.describe()

价格            节省
count      8.000000     6.000000
mean   14360.375000  1650.000000
std    20451.515934  2641.779703
min      300.000000   200.000000
25%     1025.000000   500.000000
50%     4941.500000   500.000000
75%    18500.000000  1025.000000
max    47000.000000  7000.000000

In [63]:
# 列名索引号
df.columns

Index(['出发地 ', ' 目的地', '价格 ', ' 节省', '路线名'], dtype='object')

In [64]:
# 列名值
df.columns.values

array(['出发地 ', ' 目的地', '价格 ', ' 节省', '路线名'], dtype=object)

In [68]:
col = df.columns.values
col[0].strip()

'出发地'

In [71]:
df.columns = [x.strip() for x in col]

In [72]:
df.columns.values

array(['出发地', '目的地', '价格', '节省', '路线名'], dtype=object)

In [73]:
# 统计重复值，true表示重复
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
dtype: bool

In [74]:
df.duplicated().sum()

1

In [75]:
# 显示重复的记录
df[df.duplicated()]

出发地 目的地     价格     节省        路线名
6  上海  纽约  47000  500.0  大连-烟台3天2晚

In [76]:
df.drop_duplicates()   # 显示重复待删除后的样子。

出发地  目的地     价格      节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4   NaN   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
7    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [77]:
df

出发地  目的地     价格      节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4   NaN   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
6    上海   纽约  47000   500.0        大连-烟台3天2晚
7    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [78]:
df.drop_duplicates(inplace=True)  # 真正的删除

In [79]:
df

出发地  目的地     价格      节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4   NaN   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
7    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [80]:
df.duplicated().sum()

0

In [81]:
df.shape

(7, 5)

In [82]:
df.index

Int64Index([0, 1, 2, 3, 4, 5, 7], dtype='int64')

In [86]:
df.index = range(df.shape[0])

In [87]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [88]:
df

出发地  目的地     价格      节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4   NaN   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
6    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [89]:
df.describe().T

count         mean           std    min    25%     50%     75%      max
价格    7.0  9697.571429  16883.494147  300.0  850.0  1200.0  8841.5  47000.0
节省    5.0  1880.000000   2885.654172  200.0  500.0   500.0  1200.0   7000.0

In [92]:
# 标准差（standard deviation STD）
df["价格"].std()

16883.49414721513

In [93]:
# mean 平均值
df["价格"].sum()/df["价格"].count()  # mean

9697.57142857143

In [94]:
df["价格"] - df["价格"].mean()

0    37302.428571
1    -9397.571429
2    -8497.571429
3    -9197.571429
4    -8497.571429
5     -697.571429
6    -1014.571429
Name: 价格, dtype: float64

In [95]:
# 标准分数（sta）
sta = (df["价格"] - df["价格"].mean())/df["价格"].std()
sta

0    2.209402
1   -0.556613
2   -0.503306
3   -0.544767
4   -0.503306
5   -0.041317
6   -0.060093
Name: 价格, dtype: float64

In [98]:
df[sta.abs()>2]

出发地 目的地     价格     节省        路线名
0  上海  纽约  47000  500.0  大连-烟台3天2晚

In [99]:
df[df.节省>df.价格]

出发地 目的地   价格      节省          路线名
1    北京  天津  300  7000.0   北京-秦皇岛2天2夜
3  乌鲁木齐  拉萨  500  1200.0  乌鲁木齐-拉萨2天1晚

In [102]:
pd.concat([df[sta.abs()>2],df[df.节省>df.价格]])

出发地 目的地     价格      节省          路线名
0    上海  纽约  47000   500.0    大连-烟台3天2晚
1    北京  天津    300  7000.0   北京-秦皇岛2天2夜
3  乌鲁木齐  拉萨    500  1200.0  乌鲁木齐-拉萨2天1晚

In [103]:
del_index = pd.concat([df[sta.abs()>2],df[df.节省>df.价格]]).index
del_index

Int64Index([0, 1, 3], dtype='int64')

In [104]:
# df.drop(del_index)
df.drop(del_index, inplace=True)

In [105]:
df

出发地  目的地    价格     节省              路线名
2   沈阳  NaN  1200    NaN        沈阳-青岛3天3晚
4  NaN   四川  1200  200.0    江苏-四川4天3夜4天3夜
5   南京   广州  9000    NaN  南京-广州6天5夜\t6天5夜
6   杭州   西安  8683  500.0    杭州-西安4天4夜4天4夜

In [106]:
df.shape

(4, 5)

# 查看缺失值
df.isnull() 查看空值
df.notnull()非空
df.fillna 填充


In [107]:
# 对NaN空值标注True
df.isnull()

出发地    目的地     价格     节省    路线名
2  False   True  False   True  False
4   True  False  False  False  False
5  False  False  False   True  False
6  False  False  False  False  False

In [108]:
df.isnull().sum()

出发地    1
目的地    1
价格     0
节省     2
路线名    0
dtype: int64

In [109]:
df.notnull()

出发地    目的地    价格     节省   路线名
2   True  False  True  False  True
4  False   True  True   True  True
5   True   True  True  False  True
6   True   True  True   True  True

In [110]:
df.notnull().sum()

出发地    3
目的地    3
价格     4
节省     2
路线名    4
dtype: int64

In [111]:
df[df.节省.isnull()]

出发地  目的地    价格  节省              路线名
2  沈阳  NaN  1200 NaN        沈阳-青岛3天3晚
5  南京   广州  9000 NaN  南京-广州6天5夜\t6天5夜

In [112]:
df = pd.read_csv("tr.csv")
df

出发地  目的地     价格      节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4   NaN   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
6    上海   纽约  47000   500.0        大连-烟台3天2晚
7    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [113]:
df[df.出发地.isnull()]

出发地 目的地    价格     节省            路线名
4  NaN  四川  1200  200.0  江苏-四川4天3夜4天3夜

In [114]:
df.loc[df.出发地.isnull(),"路线名"]

4    江苏-四川4天3夜4天3夜
Name: 路线名, dtype: object

In [116]:
[x.split("-")[0] for x in df.loc[df.出发地.isnull(),"路线名"]]

['江苏']

In [118]:
df.loc[df.出发地.isnull(),"出发地"] = [x.split("-")[0] for x in df.loc[df.出发地.isnull(),"路线名"]]

In [119]:
df

出发地  目的地     价格      节省              路线名
0    上海   纽约  47000   500.0        大连-烟台3天2晚
1    北京   天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  NaN   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐   拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4    江苏   四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京   广州   9000     NaN  南京-广州6天5夜\t6天5夜
6    上海   纽约  47000   500.0        大连-烟台3天2晚
7    杭州   西安   8683   500.0    杭州-西安4天4夜4天4夜

In [120]:
# 练习题，请修改目的地为NaN的值，从路线名中获取后替换。
df.loc[df.目的地.isnull(),"路线名"]

2    沈阳-青岛3天3晚
Name: 路线名, dtype: object

In [123]:
import re
re.findall("-(.*)\d天","['沈阳-青岛3天3晚']")

['青岛']

In [124]:
df.loc[df.目的地.isnull(),"目的地"] = re.findall("-(.*)\d天","['沈阳-青岛3天3晚']")

In [125]:
df


出发地 目的地     价格      节省              路线名
0    上海  纽约  47000   500.0        大连-烟台3天2晚
1    北京  天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  青岛   1200     NaN        沈阳-青岛3天3晚
3  乌鲁木齐  拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4    江苏  四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京  广州   9000     NaN  南京-广州6天5夜\t6天5夜
6    上海  纽约  47000   500.0        大连-烟台3天2晚
7    杭州  西安   8683   500.0    杭州-西安4天4夜4天4夜

In [126]:
df.describe().T

count       mean           std    min     25%     50%      75%      max
价格    8.0  14360.375  20451.515934  300.0  1025.0  4941.5  18500.0  47000.0
节省    6.0   1650.000   2641.779703  200.0   500.0   500.0   1025.0   7000.0

In [127]:
df["节省"].mean()

1650.0

In [128]:
# fillna是对空值进行填充
df["节省"].fillna(df["节省"].mean(),inplace=True)

In [129]:
df

出发地 目的地     价格      节省              路线名
0    上海  纽约  47000   500.0        大连-烟台3天2晚
1    北京  天津    300  7000.0       北京-秦皇岛2天2夜
2    沈阳  青岛   1200  1650.0        沈阳-青岛3天3晚
3  乌鲁木齐  拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚
4    江苏  四川   1200   200.0    江苏-四川4天3夜4天3夜
5    南京  广州   9000  1650.0  南京-广州6天5夜\t6天5夜
6    上海  纽约  47000   500.0        大连-烟台3天2晚
7    杭州  西安   8683   500.0    杭州-西安4天4夜4天4夜

In [130]:
df["几天几夜"] = df.路线名.str.extract("(\d天\d夜)",expand=False)

In [131]:
df["几天几夜"]

0     NaN
1    2天2夜
2     NaN
3     NaN
4    4天3夜
5    6天5夜
6     NaN
7    4天4夜
Name: 几天几夜, dtype: object

In [132]:
df

出发地 目的地     价格      节省              路线名  几天几夜
0    上海  纽约  47000   500.0        大连-烟台3天2晚   NaN
1    北京  天津    300  7000.0       北京-秦皇岛2天2夜  2天2夜
2    沈阳  青岛   1200  1650.0        沈阳-青岛3天3晚   NaN
3  乌鲁木齐  拉萨    500  1200.0      乌鲁木齐-拉萨2天1晚   NaN
4    江苏  四川   1200   200.0    江苏-四川4天3夜4天3夜  4天3夜
5    南京  广州   9000  1650.0  南京-广州6天5夜\t6天5夜  6天5夜
6    上海  纽约  47000   500.0        大连-烟台3天2晚   NaN
7    杭州  西安   8683   500.0    杭州-西安4天4夜4天4夜  4天4夜

In [134]:
df["几天几夜"].notnull().sum()

4

In [139]:
# 实战数据库数据清洗
from sqlalchemy import create_engine

In [141]:
# 初始化pymysql连接数据库
engine = create_engine('mysql+pymysql://ceshi:123456@192.168.0.233:3336/TD_OA')

In [142]:
# 读表 user表
df = pd.read_sql('user',engine)
df

UID USER_ID USER_NAME USER_NAME_INDEX      BYNAME USEING_KEY  \
0      1   admin     系统管理员     jx*t*g*l*y*       admin          0   
1     80      80        武总            w*z*      wuzong          0   
2     81      81       钮学彬         n*jx*b*   niuxuebin          0   
3     82      82       孙友磊         sx*y*l*   sunyoulei          0   
4     83      83       经雨晨          j*y*c*  jingyvchen          0   
..   ...     ...       ...             ...         ...        ...   
256  367     367       罗凯文          l*k*w*   luokaiwen          0   
257  368     368       孙佳伟         sx*j*w*   sunjiawei          0   
258  369     369        季舟            j*z*      jizhou          0   
259  370     370       顾佳珺          g*j*j*    gujiajun          0   
260  371     371       秦颖蕾          q*y*l*  qinyinglei          0   

    USING_FINGER                            PASSWORD KEY_SN SECURE_KEY_SN  \
0              0  $1$sL2.ak/.$k19PAiaGp58AUrbSWbvlz/                        
1              0  $1$JH..6M1.$.ud1bz9ESKuYnz3gfhdx61                        
2              0  $1$x7/.zU/.$CQNBeol5OtcNTiiracnhU.                        
3              0  $1$5b0.bX..$qkd.cr15UrXKn60VGr1Vr.                        
4              0  $1$UP4.L90.$5yfIlCyOVkomZfdZHz73z1                        
..           ...                                 ...    ...           ...   
256            0  $1$Ps1.xE..$LwfpxkyxypLlDA3qb0bk51                        
257            0  $1$71..SK0.$.iURjVY37j1YqxejM0sT21                        
258            0  $1$gd2.4n3.$CTpLIhdQqoVb5YCWiC0TD0                        
259            0  $1$Ps1.xE..$LwfpxkyxypLlDA3qb0bk51                        
260            0  $1$N33.Jn3.$MoMTqLXe3ZW0mlnzdH8h11                        

     ...  USER_MANAGE_ORGS  DEVICE_NUMBER MOBIL_NO_BD corp_id ATTENDANCE_ID  \
0    ...                                                                  0   
1    ...                                                                  0   
2    ...                                                               9915   
3    ...                                                                  0   
4    ...                                                                  0   
..   ...               ...            ...         ...     ...           ...   
256  ...                                                                117   
257  ...                                                                122   
258  ...                                                                  0   
259  ...                                                                126   
260  ...                                                                127   

                          VX_MARK  IMEI     MODEL PLATFORM  \
0                            None  None      None     None   
1                            None  None      None     None   
2    oW62u4gB1Mmj_ISUObUQmriK1AmA  null  LIO-AN00  android   
3                            None  None      None     None   
4                            None  None      None     None   
..                            ...   ...       ...      ...   
256                          None  None      None            
257                          None  None      None            
258                          None  None      None            
259                          None  None      None            
260                          None  None      None            

                          UNIONID  
0                                  
1                                  
2    oKsp-t3C1TbugQdMGTEMvAQA_sbA  
3                                  
4                                  
..                            ...  
256                                
257                                
258                                
259                                
260                                

[261 rows x 83 columns]

In [144]:
with engine.connect() as con:
    con.execute("DROP TABLE if exists 100user")
    con.execute("create table 100user like user;")
df.to_sql("100user", engine, index=False, if_exists="append")

In [145]:
# 读表 100user
cmd = "select * from 100user"
df = pd.read_sql(sql=cmd, con=engine)

In [146]:
print(df.head())

   UID USER_ID USER_NAME USER_NAME_INDEX      BYNAME USEING_KEY USING_FINGER  \
0    1   admin     系统管理员     jx*t*g*l*y*       admin          0            0   
1   80      80        武总            w*z*      wuzong          0            0   
2   81      81       钮学彬         n*jx*b*   niuxuebin          0            0   
3   82      82       孙友磊         sx*y*l*   sunyoulei          0            0   
4   83      83       经雨晨          j*y*c*  jingyvchen          0            0   

                             PASSWORD KEY_SN SECURE_KEY_SN  ...  \
0  $1$sL2.ak/.$k19PAiaGp58AUrbSWbvlz/                       ...   
1  $1$JH..6M1.$.ud1bz9ESKuYnz3gfhdx61                       ...   
2  $1$x7/.zU/.$CQNBeol5OtcNTiiracnhU.                       ...   
3  $1$5b0.bX..$qkd.cr15UrXKn60VGr1Vr.                       ...   
4  $1$UP4.L90.$5yfIlCyOVkomZfdZHz73z1                       ...   

   USER_MANAGE_ORGS  DEVICE_NUMBER MOBIL_NO_BD corp_id ATTENDANCE_ID  \
0                                           

In [147]:
print(df["USER_NAME"][0])

系统管理员


In [148]:
# imei
# 获取用户为名，条件是imei为非空
x = df.loc[df.IMEI.notnull(),"USER_NAME"]
x

2      钮学彬
5      黄新晖
6       刘挺
7      饶顺荣
8       薛伟
      ... 
245    陈炳忠
247    胡正茂
249     徐良
251     陆敏
253    邓海庚
Name: USER_NAME, Length: 136, dtype: object

In [149]:
df.loc[df.IMEI.notnull(), "USER_NAME"] = [i + "NULL" for i in x]

In [158]:
df

UID USER_ID USER_NAME USER_NAME_INDEX      BYNAME USEING_KEY  \
0      1   admin     系统管理员     jx*t*g*l*y*       admin          0   
1     80      80        武总            w*z*      wuzong          0   
2     81      81   钮学彬NULL         n*jx*b*   niuxuebin          0   
3     82      82       孙友磊         sx*y*l*   sunyoulei          0   
4     83      83       经雨晨          j*y*c*  jingyvchen          0   
..   ...     ...       ...             ...         ...        ...   
256  367     367       罗凯文          l*k*w*   luokaiwen          0   
257  368     368       孙佳伟         sx*j*w*   sunjiawei          0   
258  369     369        季舟            j*z*      jizhou          0   
259  370     370       顾佳珺          g*j*j*    gujiajun          0   
260  371     371       秦颖蕾          q*y*l*  qinyinglei          0   

    USING_FINGER                            PASSWORD KEY_SN SECURE_KEY_SN  \
0              0  $1$sL2.ak/.$k19PAiaGp58AUrbSWbvlz/                        
1              0  $1$JH..6M1.$.ud1bz9ESKuYnz3gfhdx61                        
2              0  $1$x7/.zU/.$CQNBeol5OtcNTiiracnhU.                        
3              0  $1$5b0.bX..$qkd.cr15UrXKn60VGr1Vr.                        
4              0  $1$UP4.L90.$5yfIlCyOVkomZfdZHz73z1                        
..           ...                                 ...    ...           ...   
256            0  $1$Ps1.xE..$LwfpxkyxypLlDA3qb0bk51                        
257            0  $1$71..SK0.$.iURjVY37j1YqxejM0sT21                        
258            0  $1$gd2.4n3.$CTpLIhdQqoVb5YCWiC0TD0                        
259            0  $1$Ps1.xE..$LwfpxkyxypLlDA3qb0bk51                        
260            0  $1$N33.Jn3.$MoMTqLXe3ZW0mlnzdH8h11                        

     ...  USER_MANAGE_ORGS  DEVICE_NUMBER MOBIL_NO_BD corp_id ATTENDANCE_ID  \
0    ...                                                                  0   
1    ...                                                                  0   
2    ...                                                               9915   
3    ...                                                                  0   
4    ...                                                                  0   
..   ...               ...            ...         ...     ...           ...   
256  ...                                                                117   
257  ...                                                                122   
258  ...                                                                  0   
259  ...                                                                126   
260  ...                                                                127   

                          VX_MARK  IMEI     MODEL PLATFORM  \
0                            None  None      None     None   
1                            None  None      None     None   
2    oW62u4gB1Mmj_ISUObUQmriK1AmA  null  LIO-AN00  android   
3                            None  None      None     None   
4                            None  None      None     None   
..                            ...   ...       ...      ...   
256                          None  None      None            
257                          None  None      None            
258                          None  None      None            
259                          None  None      None            
260                          None  None      None            

                          UNIONID  
0                                  
1                                  
2    oKsp-t3C1TbugQdMGTEMvAQA_sbA  
3                                  
4                                  
..                            ...  
256                                
257                                
258                                
259                                
260                                

[261 rows x 83 columns]

In [155]:
# df.to_sql('101user', engine, index=True, if_exists='append')